<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TheorySubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('wbscte_other_diploma_paper_theory_master')->insert([
            [
                'course_id' => '1',
                'paper_code' => 'HMCT-101',
                'paper_name' => 'COMMUNICATION SKILLS IN ENGLISH - 1',
                'inst_id' => '1',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '2',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '1',
                'paper_code' => 'HMCT-102',
                'paper_name' => 'FOOD & BEVERAGE SERVICE-I',
                'inst_id' => '1',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '4',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '1',
                'paper_code' => 'HMCT-103',
                'paper_name' => 'FOOD PRODUCTION-I',
                'inst_id' => '1',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '4',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '1',
                'paper_code' => 'HMCT-104',
                'paper_name' => 'ACCOMODATION OPERATION-I',
                'inst_id' => '1',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '1',
                'paper_code' => 'HMCT-105',
                'paper_name' => 'COMPUTER FUNDAMENTALS -1',
                'inst_id' => '1',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '2',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '2',
                'paper_code' => 'HMCT-101',
                'paper_name' => 'COMMUNICATION SKILLS IN ENGLISH - 1',
                'inst_id' => '2',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '2',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '2',
                'paper_code' => 'HMCT-102',
                'paper_name' => 'FOOD & BEVERAGE SERVICE-I',
                'inst_id' => '2',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '4',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '2',
                'paper_code' => 'HMCT-103',
                'paper_name' => 'FOOD PRODUCTION-I',
                'inst_id' => '2',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '4',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '2',
                'paper_code' => 'HMCT-104',
                'paper_name' => 'ACCOMODATION OPERATION-I',
                'inst_id' => '2',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '2',
                'paper_code' => 'HMCT-105',
                'paper_name' => 'COMPUTER FUNDAMENTALS -1',
                'inst_id' => '2',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '2',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '3',
                'paper_code' => '5.GV.01',
                'paper_name' => 'Basics of Refrigeration',
                'inst_id' => '3',
                'paper_semester' => 'V',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '3',
                'paper_code' => '5.GV.02',
                'paper_name' => 'Basics of Air Conditioning',
                'inst_id' => '3',
                'paper_semester' => 'V',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '3',
                'paper_code' => '5.GV.03',
                'paper_name' => 'Engineering Material',
                'inst_id' => '3',
                'paper_semester' => 'V',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '3',
                'paper_code' => '5.GV.04',
                'paper_name' => 'Soldering & De-Soldering of Components & Emergency actions II',
                'inst_id' => '3',
                'paper_semester' => 'V',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '4',
                'paper_code' => '4.GV.04',
                'paper_name' => 'General Foundation Course –II',
                'inst_id' => '4',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '4',
                'paper_code' => '4.GV.05',
                'paper_name' => 'Manufacturing Technology - II',
                'inst_id' => '4',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '4',
                'paper_code' => '4.GV.06',
                'paper_name' => 'Material Science and Material',
                'inst_id' => '4',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '4',
                'paper_code' => '4.GV.07',
                'paper_name' => 'Motor Vehicle Technology -I',
                'inst_id' => '4',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '4',
                'paper_code' => '5.GV.01',
                'paper_name' => 'Motor Vehicle Technology -II',
                'inst_id' => '4',
                'paper_semester' => 'V',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '4',
                'paper_code' => '5.GV.02',
                'paper_name' => 'Automobile Electrical Equipment',
                'inst_id' => '4',
                'paper_semester' => 'V',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '4',
                'paper_code' => '5.GV.03',
                'paper_name' => 'Two and Three Wheeler',
                'inst_id' => '4',
                'paper_semester' => 'V',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '4',
                'paper_code' => '5.GV.04',
                'paper_name' => 'Modern Electric & Hybrid Vehicles',
                'inst_id' => '4',
                'paper_semester' => 'V',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '5',
                'paper_code' => '4.GV.04',
                'paper_name' => 'General Foundation Course –II',
                'inst_id' => '4',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '5',
                'paper_code' => '4.GV.05',
                'paper_name' => 'Digital Electronics',
                'inst_id' => '4',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '5',
                'paper_code' => '4.GV.06',
                'paper_name' => 'Trouble Shooting & Maintenance of Electronics Equipment’s-II',
                'inst_id' => '4',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '5',
                'paper_code' => '4.GV.07',
                'paper_name' => 'IT Tools –II',
                'inst_id' => '4',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '5',
                'paper_code' => '3GE.01',
                'paper_name' => 'LANGUAGE-I',
                'inst_id' => '4',
                'paper_semester' => 'I',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '5',
                'paper_code' => '4.GE.01',
                'paper_name' => 'LANGUAGE-II',
                'inst_id' => '4',
                'paper_semester' => 'III',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '3.GE.01',
                'paper_name' => 'Language – I',
                'inst_id' => '5',
                'paper_semester' => 'I',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '3.GE.02',
                'paper_name' => 'Applied Chemistry',
                'inst_id' => '5',
                'paper_semester' => 'I',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '3.GE.03',
                'paper_name' => 'Applied Physics',
                'inst_id' => '5',
                'paper_semester' => 'I',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '3.GE.04',
                'paper_name' => 'Applied Mathematics-I',
                'inst_id' => '5',
                'paper_semester' => 'I',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '3.GV.01',
                'paper_name' => 'General Foundation Course',
                'inst_id' => '5',
                'paper_semester' => 'II',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '3.GV.02',
                'paper_name' => 'Basic Electricity and Electronics',
                'inst_id' => '5',
                'paper_semester' => 'II',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '3.GE.05',
                'paper_name' => 'Language – II',
                'inst_id' => '5',
                'paper_semester' => 'II',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '3.GE.06',
                'paper_name' => 'Applied Mathematics -II',
                'inst_id' => '5',
                'paper_semester' => 'II',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '4.GV.05',
                'paper_name' => 'Data Structures & Algorithms',
                'inst_id' => '5',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '4.GV.06',
                'paper_name' => 'Database Management Systems',
                'inst_id' => '5',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '4.GV.07',
                'paper_name' => 'Computer Networks',
                'inst_id' => '5',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '6',
                'paper_code' => '4.GV.08',
                'paper_name' => 'Computer Organization & Architecture',
                'inst_id' => '5',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '7',
                'paper_code' => '4.GV.05',
                'paper_name' => 'Data Structures and Design Analysis of Algorithms',
                'inst_id' => '5',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '7',
                'paper_code' => '4.GV.06',
                'paper_name' => 'Tools, Equipment & Safety Measures',
                'inst_id' => '5',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '7',
                'paper_code' => '4.GV.07',
                'paper_name' => 'Robotic Engineering',
                'inst_id' => '5',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '7',
                'paper_code' => '4.GV.08',
                'paper_name' => 'Human-Computer Interaction',
                'inst_id' => '5',
                'paper_semester' => 'IV',
                'paper_type' => 'Half Paper',
                'paper_credit' => '3',
                'paper_full_marks' => '50',
                'paper_internal_marks' => '15',
                'paper_external_marks' => '35',
                'paper_pass_marks' => '20',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '8',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '8',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '8',
                'paper_code' => 'IS-103',
                'paper_name' => 'Appraisal, Analysis, Inspection & Quality Control Procedures',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '8',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '9',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '9',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '9',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '9',
                'paper_code' => 'IS203',
                'paper_name' => 'Chemical Safety in Industry',
                'inst_id' => '6',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '9',
                'paper_code' => 'IS204',
                'paper_name' => 'Safety in Construction Industry',
                'inst_id' => '6',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '9',
                'paper_code' => 'IS205',
                'paper_name' => 'Applied Ergonomics',
                'inst_id' => '6',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '9',
                'paper_code' => 'IS206/5',
                'paper_name' => 'Fire Safety in Industry (Elective)',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '10',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '7',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '10',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '7',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '10',
                'paper_code' => 'IS-103',
                'paper_name' => 'Appraisal, Analysis, Inspection & Quality Control Procedures',
                'inst_id' => '7',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '10',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '7',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '11',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '11',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '11',
                'paper_code' => 'IS-103',
                'paper_name' => 'Appraisal, Analysis, Inspection & Quality Control Procedures',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '11',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '12',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '12',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '12',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '12',
                'paper_code' => 'IS203',
                'paper_name' => 'Chemical Safety in Industry',
                'inst_id' => '8',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '12',
                'paper_code' => 'IS204',
                'paper_name' => 'Safety in Construction Industry',
                'inst_id' => '8',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '12',
                'paper_code' => 'IS205',
                'paper_name' => 'Applied Ergonomics',
                'inst_id' => '8',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '12',
                'paper_code' => 'IS206/5',
                'paper_name' => 'Fire Safety in Industry (Elective)',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '13',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '9',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '13',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '9',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '13',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '9',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '13',
                'paper_code' => 'IS203',
                'paper_name' => 'Chemical Safety in Industry',
                'inst_id' => '9',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '13',
                'paper_code' => 'IS204',
                'paper_name' => 'Safety in Construction Industry',
                'inst_id' => '9',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '13',
                'paper_code' => 'IS205',
                'paper_name' => 'Applied Ergonomics',
                'inst_id' => '9',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '13',
                'paper_code' => 'IS206/5',
                'paper_name' => 'Fire Safety in Industry (Elective)',
                'inst_id' => '9',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '14',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '10',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '14',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '10',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '14',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '10',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '14',
                'paper_code' => 'IS203',
                'paper_name' => 'Chemical Safety in Industry',
                'inst_id' => '10',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '14',
                'paper_code' => 'IS204',
                'paper_name' => 'Safety in Construction Industry',
                'inst_id' => '10',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '14',
                'paper_code' => 'IS205',
                'paper_name' => 'Applied Ergonomics',
                'inst_id' => '10',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '14',
                'paper_code' => 'IS206/5',
                'paper_name' => 'Fire Safety in Industry (Elective)',
                'inst_id' => '10',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '15',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '11',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '15',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '11',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '15',
                'paper_code' => 'IS-103',
                'paper_name' => 'Appraisal, Analysis, Inspection & Quality Control Procedures',
                'inst_id' => '11',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '15',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '11',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],

            [
                'course_id' => '16',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '12',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '16',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '12',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '16',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '12',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '16',
                'paper_code' => 'IS203',
                'paper_name' => 'Chemical Safety in Industry',
                'inst_id' => '12',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '16',
                'paper_code' => 'IS204',
                'paper_name' => 'Safety in Construction Industry',
                'inst_id' => '12',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '16',
                'paper_code' => 'IS205',
                'paper_name' => 'Applied Ergonomics',
                'inst_id' => '12',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '16',
                'paper_code' => 'IS206/5',
                'paper_name' => 'Fire Safety in Industry (Elective)',
                'inst_id' => '12',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '17',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '13',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '17',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '13',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '17',
                'paper_code' => 'IS-103',
                'paper_name' => 'Appraisal, Analysis, Inspection & Quality Control Procedures',
                'inst_id' => '13',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '17',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '13',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '18',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '14',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '18',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '14',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '18',
                'paper_code' => 'IS-103',
                'paper_name' => 'Appraisal, Analysis, Inspection & Quality Control Procedures',
                'inst_id' => '14',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '18',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '14',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '19',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '15',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '19',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '15',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '19',
                'paper_code' => 'IS-103',
                'paper_name' => 'Appraisal, Analysis, Inspection & Quality Control Procedures',
                'inst_id' => '15',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '19',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '15',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '20',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '16',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '20',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '16',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '20',
                'paper_code' => 'IS-103',
                'paper_name' => 'Appraisal, Analysis, Inspection & Quality Control Procedures',
                'inst_id' => '16',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '20',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '16',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '21',
                'paper_code' => 'IS-101',
                'paper_name' => 'Safety, Health & Environmental Management',
                'inst_id' => '17',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '21',
                'paper_code' => 'IS-102',
                'paper_name' => 'Safety Engineering',
                'inst_id' => '17',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '21',
                'paper_code' => 'IS-104',
                'paper_name' => 'Industrial Hygiene, Occupational Health & Applied Ergonomics',
                'inst_id' => '17',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '21',
                'paper_code' => 'IS203',
                'paper_name' => 'Chemical Safety in Industry',
                'inst_id' => '17',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '21',
                'paper_code' => 'IS204',
                'paper_name' => 'Safety in Construction Industry',
                'inst_id' => '17',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '21',
                'paper_code' => 'IS205',
                'paper_name' => 'Applied Ergonomics',
                'inst_id' => '17',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '21',
                'paper_code' => 'IS206/5',
                'paper_name' => 'Fire Safety in Industry (Elective)',
                'inst_id' => '17',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '22',
                'paper_code' => 'FSM–101',
                'paper_name' => 'Basics of Fire Science',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '22',
                'paper_code' => 'FSM–102',
                'paper_name' => 'Fire Risk in Hazardous Elements',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '22',
                'paper_code' => 'FSM–103',
                'paper_name' => 'Fire Fighting Agents & Appliances',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '22',
                'paper_code' => 'FSM–104',
                'paper_name' => 'Fundamentals of Fire Protection & Control Technology',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '22',
                'paper_code' => 'FSM–105',
                'paper_name' => 'Fire Safety in Buildings',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '22',
                'paper_code' => 'FSM–106',
                'paper_name' => 'Fundamentals of Industrial Safety',
                'inst_id' => '6',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '23',
                'paper_code' => 'FSM–101',
                'paper_name' => 'Basics of Fire Science',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '23',
                'paper_code' => 'FSM–102',
                'paper_name' => 'Fire Risk in Hazardous Elements',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '23',
                'paper_code' => 'FSM–103',
                'paper_name' => 'Fire Fighting Agents & Appliances',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '23',
                'paper_code' => 'FSM–104',
                'paper_name' => 'Fundamentals of Fire Protection & Control Technology',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '23',
                'paper_code' => 'FSM–105',
                'paper_name' => 'Fire Safety in Buildings',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '23',
                'paper_code' => 'FSM–106',
                'paper_name' => 'Fundamentals of Industrial Safety',
                'inst_id' => '8',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '24',
                'paper_code' => 'FSM–101',
                'paper_name' => 'Basics of Fire Science',
                'inst_id' => '16',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '24',
                'paper_code' => 'FSM–102',
                'paper_name' => 'Fire Risk in Hazardous Elements',
                'inst_id' => '16',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '24',
                'paper_code' => 'FSM–103',
                'paper_name' => 'Fire Fighting Agents & Appliances',
                'inst_id' => '16',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '24',
                'paper_code' => 'FSM–104',
                'paper_name' => 'Fundamentals of Fire Protection & Control Technology',
                'inst_id' => '16',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '24',
                'paper_code' => 'FSM–105',
                'paper_name' => 'Fire Safety in Buildings',
                'inst_id' => '16',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '24',
                'paper_code' => 'FSM–106',
                'paper_name' => 'Fundamentals of Industrial Safety',
                'inst_id' => '16',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '25',
                'paper_code' => 'FSM–101',
                'paper_name' => 'Basics of Fire Science',
                'inst_id' => '18',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '25',
                'paper_code' => 'FSM–102',
                'paper_name' => 'Fire Risk in Hazardous Elements',
                'inst_id' => '18',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '25',
                'paper_code' => 'FSM–103',
                'paper_name' => 'Fire Fighting Agents & Appliances',
                'inst_id' => '18',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '25',
                'paper_code' => 'FSM–104',
                'paper_name' => 'Fundamentals of Fire Protection & Control Technology',
                'inst_id' => '18',
                'paper_semester' => 'I',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '30',
                'paper_external_marks' => '70',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '25',
                'paper_code' => 'FSM203',
                'paper_name' => 'Fire Prevention & Life Safety',
                'inst_id' => '18',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '20',
                'paper_external_marks' => '80',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '25',
                'paper_code' => 'FSM204',
                'paper_name' => 'Fire Risk Assessment, Fire Safety Audit & Fire Investigation',
                'inst_id' => '18',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '20',
                'paper_external_marks' => '80',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '25',
                'paper_code' => 'FSM205',
                'paper_name' => 'Design Engineering and Drawing of Fire Preotection System',
                'inst_id' => '18',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '20',
                'paper_external_marks' => '80',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],
            [
                'course_id' => '25',
                'paper_code' => 'FSM206',
                'paper_name' => 'Fire Safety Management Legislation',
                'inst_id' => '18',
                'paper_semester' => 'III',
                'paper_type' => 'Full Paper',
                'paper_credit' => '0',
                'paper_full_marks' => '100',
                'paper_internal_marks' => '20',
                'paper_external_marks' => '80',
                'paper_pass_marks' => '40',
                'paper_affiliation_year' => '2023-24'
            ],



        ]);
    }
}
